platform :ios, '9.0'
use_frameworks!
install! 'cocoapods',
         :deterministic_uuids => false

target 'example' do
  rn_path = '../node_modules/react-native'

  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  # pod 'React', :path => rn_path, :subspecs => [
  pod 'React', :path => "#{rn_path}/React.podspec", :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'CxxBridge',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../..'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'YPImagePicker'

end


swift4Targets = ['YPImagePicker', 'SteviaLayout']
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if swift4Targets.include? target.name
                config.build_settings['SWIFT_VERSION'] = '4'
            else
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end